service: onchain-voting-lucid-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: production
  profile: 'ddz-onchain-voting'
  region: us-east-1
  memorySize: 128

functions:
  api:
    handler: app.handler
    environment: ${file(env.json)}
    events:
      - httpApi: '*'
